### PR TITLE
add buyramburn

### PR DESCRIPTION
**Pull request by rdewilder**
## Change Description

Add buyramburn action to eosio.system contract to allows users to buy RAM and immediately burn it

## Deployment Changes
- [ ] Deployment Changes

## API Changes
- [ ] API Changes

## Documentation Additions
- [ ] Documentation Additions

### CODE REVIEW

**Review by DenisCarriere — APPROVED** [review]
Missing Ricardian contract for new action

**Comment by DenisCarriere** [comment]
Looks good to me 👍

**Comment by learnforpractice** [comment]
What the heck are you guys doing here?

**Comment by learnforpractice** [comment]
Doesn't that cause enough chaos already?

**Comment by learnforpractice** [comment]
What's Plan B when EOS becomes unusable, hmm?

**Pull request merged**
