### PR TITLE
Split system_tests into multiple suites such that each of them can finish CICD testing in time

### PR DESCRIPTION
**Pull request by linh2931**
Resolved https://github.com/AntelopeIO/reference-contracts/issues/99.

Fixed test failure in Spring https://github.com/AntelopeIO/spring/issues/254

## Deployment Changes
- [ ] Deployment Changes

## API Changes
- [ ] API Changes

## Documentation Additions
- [ ] Documentation Additions

### CODE REVIEW

**Comment by spoonincode** [comment]
What caused the ballooning of system_tests execution time? It's nearly 7x from what it was before switching to the new testers in #95. I'm not surprised to see something like 2x but 7x is a bit surprising considering it doesn't look like we added any new tests or such in #95.

**Comment by linh2931** [comment]
> What caused the ballooning of system_tests execution time? It's nearly 7x from what it was before switching to the new testers in #95. I'm not surprised to see something like 2x but 7x is a bit surprising considering it doesn't look like we added any new tests or such in #95.

I am digging it deeper on the cause. Thanks.

**Comment by linh2931** [comment]
Initial numbers when running `eosio_system_tests` with `time` command on my Ubuntu22 box:

* Legacy tester: `6m32.055s`
* Savanna tester with 4 local BLS keys (current implementation): `18m19.707s`
* Savanna tester with 1 local BLS key: `13m31.346s`

Looking into why even 1 key doubles the test time.

**Comment by linh2931** [comment]
Configuring only one local finalizer helps to reduce system_tests to run in 7 minutes in CICD https://github.com/AntelopeIO/spring/pull/266.

Close this PR for now.

**Pull request closed without merging**
